[project]
name = "sentiment-analysis-using-rnn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "pandas>=2.3.3",
    "streamlit>=1.52.2",
    "tensorflow>=2.20.0",
]
